
const BASE_BACK_END_URL = "http://localhost:8080/api/v1/";
const DEFAULT_TIMEOUT = 8000;
const RESPONSE_DELAY = 2000;
///
const DEFAULT_PAGE = 0;
const DEFAULT_SIZE = 10;
///

export { BASE_BACK_END_URL, DEFAULT_TIMEOUT, RESPONSE_DELAY, DEFAULT_PAGE, DEFAULT_SIZE }