export { default as useData } from './useDataPost'
export { default as useFetchById } from './useFetchById'
export { default as useFetchList } from './useFetchList'
export { default as useQuery } from './useQuery'
export { default as useGetData } from './useGET'
