
const TOASTIFY_SUCCESS = "TOASTIFY_SUCCESS";
const TOASTIFY_ERROR = "TOASTIFY_ERROR";
const TOASTIFY_WARNING = "TOASTIFY_WARNING";
const TOASTIFY_INFO = "TOASTIFY_INFO";

export { TOASTIFY_SUCCESS, TOASTIFY_ERROR, TOASTIFY_WARNING, TOASTIFY_INFO }